services:
  postgres:
    image: postgres:13.16
    container_name: postgres
    environment:
    #FIXME ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
    #DO NOT USE IN PRODUCTION 
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=baghive_db
      - PGDATA=/var/lib/postgresql/data
    #FIXME ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
    ports:
      - "5432:5432"
    # volumes:
    #   - type: bind
    #     source: ./config/postgres/schema.sql
    #     target: /docker-entrypoint-initdb.d/schema.sql
    #   - type: bind
    #     source: ./postgres-data
    #     target: /var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]
