version: '3.0'
services:
  pulsar:
    image: apachepulsar/pulsar-all:3.3.1
    container_name: pulsar-all
    replace: always
    ports:
      - "6680:8080"
      - "6650:6650"
    volumes:
      - ./config/pulsar/broker.conf:/conf/broker.conf
    command: bin/pulsar standalone

  postgres:
    image: postgres:13
    container_name: postgres
    replace: always
    environment:
    #FIXME: DO NOT USE IN PRODUCTION 
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=baghive_db
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
    #FIXME: make location of the volume on the host configurable
      - ./postgres-data:/var/lib/postgresql/data
      - ./config/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]
