version: '3.0'
services:
  pulsar:
    image: apachepulsar/pulsar-all:3.3.1
    container_name: pulsar-all
    restart: always
    ports:
      - "6680:8080"
      - "6650:6650"
    volumes:
      - ./config/pulsar/broker.conf:/conf/broker.conf
    command: bin/pulsar standalone

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    secrets:
      - postgres-creds
    environment:
      - POSTGRES_USER=/run/secrets/postgres-creds:POSTGRES_USER
      - POSTGRES_PASSWORD=/run/secrets/postgres-creds:POSTGRES_PASSWORD
      - POSTGRES_DB=/run/secrets/postgres-creds:POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./config/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]

secrets:
  postgres-creds:
    external: true