version: '3.0'
services:
  pulsar:
    image: apachepulsar/pulsar-all:3.3.1
    container_name: pulsar-all
    restart: always
    ports:
      - "6680:8080"
      - "6650:6650"
    volumes:
      - ./config/pulsar/broker.conf:/conf/broker.conf
    command: bin/pulsar standalone

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
